server.port=8081

# ${ENVIRONMENT_VARIABLE_NAME:Default_Value} ක්‍රමය
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/task_manager?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:yasindu}
spring.datasource.password=${DB_PASS:yasindusql}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true